### ISSUE TITLE
Please use Java built-in HttpClient instead of bringing a okhttp3 dependency

### ISSUE THREAD

**Issue by tenor-dev** [web-eid/web-eid-authtoken-validation-java#31]
Java 9+ has a good built-in HttpClient, so that external http client dependencies are not needed.

You can keep current OcspClientImpl as an optional implementation for those still needing Java 8 support, or implement it using HttpURLConnection, which is available since Java 1.0

**Comment by tenor-dev** [comment]
There is also no way of configuring http/https proxy currently for the internally used okhttp3.

**Comment by mrts** [comment]
> Java 9+ has a good built-in HttpClient, so that external http client dependencies are not needed.

Thank you, good point! I very much agree, but we need to support Java 8.

> You can keep current OcspClientImpl as an optional implementation for those still needing Java 8 support, or implement it using HttpURLConnection, which is available since Java 1.0

Leaving the HttpURLConnection suggestion aside, how would you implement a solution that provides the current OkHttp-based implementation for projects using Java 8 and HttpClient-based implementation for projects using Java 9+ in the current codebase? [Multi-release JARs are an option](https://www.baeldung.com/java-multi-release-jar), but [Maven support for them](https://maven.apache.org/plugins/maven-compiler-plugin/multirelease.html) [is rather complicated](https://in.relation.to/2017/02/13/building-multi-release-jars-with-maven/). (I found an [article by a RedHat engineer](https://word-bits.flurg.com/multrelease-jars/) that looks promising though.)

> There is also no way of configuring http/https proxy currently for the internally used okhttp3.

Thanks for bringing this up! We can add proxy support to `AuthTokenValidationConfiguration` (and `AuthTokenValidatorBuilder`) if needed. Were pointing out the limitations of the current approach or do you need it?

**Comment by tenor-dev** [comment]
What's wrong with HttpURLConnection? It actually uses Java 9 HttpClient inside if used from Java 9 or later.
It also respects system-wide proxy settings, basically works as expected.

And yes, we do need the proxy, as SK does IP-based billing for OCSP requests and it's impossible to use it from cloud providers, who don't guarantee outbound static IPs. That's why often a proxy with static IP is needed for talking with SK services.

As for how to provide different implementations:
* The simplest solution is to provide both classes in the jar, but declare okhttp as implementation (compile-only) dependency, so that clients will not get it by default, and document that the dependency must be added to the project to use the OkHttp-based implemenbtation. Then there could be a setter to choose the OCSP implementation in code.
* Another solution is to yes is to use ServiceLocator to choose the OCSP client implementation, provide the default (e.g. HttpURLConnection-based) implementation. Then create a simple sub-project with dependency on okhttp, the implementation class and ServiceLocator declaration in manifest that will enable it automatically, if it's in classpath

Both approaches seem easy. But the third approach is to leave only HttpURLConnection implementation and make all users happy at once :-)

**Comment by mrts** [comment]
> What's wrong with HttpURLConnection? It actually uses Java 9 HttpClient inside if used from Java 9 or later.
It also respects system-wide proxy settings, basically works as expected.

OkHttp by default uses [connection pooling](https://square.github.io/okhttp/contribute/concurrency/#connection-pool), [recovers from common connection problems](https://square.github.io/okhttp/) and has a fluent API via a single, efficient, thread-safe [HTTP client instance](https://github.com/web-eid/web-eid-authtoken-validation-java/blob/main/src/main/java/eu/webeid/security/validator/AuthTokenValidatorImpl.java#L66-L70). HttpURLConnection does support connection pooling to some extent, but it is [more fragile](https://dzone.com/articles/caveats-httpurlconnection), neither does it provide access to a HTTP client instance.

> And yes, we do need the proxy, as SK does IP-based billing for OCSP requests and it's impossible to use it from cloud providers, who don't guarantee outbound static IPs. That's why often a proxy with static IP is needed for talking with SK services.

Understood. Is adding proxy support to `AuthTokenValidationConfiguration` (and `AuthTokenValidatorBuilder`) for configuring the OkHttp proxy enough for now or would you still suggest that we drop OkHttp and use HttpURLConnection despite the reasoning above?

> As for how to provide different implementations:

Thank you, both options are possible. However, they both increase the complexity of the solution. Maybe the best path forward is to drop Java 8 compatibility in a future major version and switch to the built-in HttpClient then?

> make all users happy at once :-)

We definitely want to assure that all our users are happy :-)!

**Comment by tenor-dev** [comment]
It's not easy to setup a ProxySelector to enable proxy for OCSP only.
For that, we need to know precisely the URLs the library is going to connect to, and maybe even create our own implementaton of ProxySelector to have a fine level of control. Will need to test this.

Anyway, the major problem is that every library brings it's own non-standard http client nowadays and your project ends up containing multiple single-use full-blown http client implementations, in addition to the standard one. For example, digidoc4j that should be used together with this library uses apache httpclient. Selenium brings netty, etc. In the end, you can a huge bloat of jars for your project.

Currently we depend on this library like this:
```
  implementation("org.webeid.security:authtoken-validation:2.0.1") {
    exclude("com.squareup.okhttp3")
  }
```

That works with `withoutUserCertificateRevocationCheckWithOcsp()`, but it would be very nice to have `withOcspViaStandardJavaHttpClient()` instead :-)

**Comment by tenor-dev** [comment]
@mrts we have tried configuring a global implementation ProxySelctor. The okhttp3 does call it's `select` method indeed, but there's a problem.

* If we return an empty list from `select`, then the request works without a proxy, as expected
* If we return List.of(NO_PROXY) - which is correct according to ProxySelector docs, then it fails with a cancel/timeout exception.
* If we provide it a real proxy, then again it fails with a cancel/timeout

That means that trying to use a proxy actually doesn't work...

Stack trace for both cases:
```
14126 [6b36-2] INFO AuthTokenValidatorImpl - Starting token validation
19316 [6b36-2] WARN AuthTokenValidatorImpl - Token validation was interrupted:: eu.webeid.security.exceptions.UserCertificateOCSPCheckFailedException: User certificate revocation check has failed
  at eu.webeid.security.validator.certvalidators.SubjectCertificateNotRevokedValidator.validateCertificateNotRevoked(SubjectCertificateNotRevokedValidator.java:113)
  at eu.webeid.security.validator.certvalidators.SubjectCertificateValidatorBatch.executeFor(SubjectCertificateValidatorBatch.java:41)
  at eu.webeid.security.validator.AuthTokenValidatorImpl.validateToken(AuthTokenValidatorImpl.java:160)
  at eu.webeid.security.validator.AuthTokenValidatorImpl.validate(AuthTokenValidatorImpl.java:120)
  at signing.WebEidClient.auth(WebEidClient.kt:40)
  at auth.AuthRoutes.webEIdLogin(AuthRoutes.kt:55)
  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
  at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.base/java.lang.reflect.Method.invoke(Method.java:568)
  at kotlin.reflect.jvm.internal.calls.CallerImpl$Method.callMethod(CallerImpl.kt:97)
  at kotlin.reflect.jvm.internal.calls.CallerImpl$Method$Instance.call(CallerImpl.kt:113)
  at kotlin.reflect.jvm.internal.KCallableImpl.call(KCallableImpl.kt:108)
  at kotlin.reflect.jvm.internal.KCallableImpl.callDefaultMethod$kotlin_reflection(KCallableImpl.kt:159)
  at kotlin.reflect.jvm.internal.KCallableImpl.callBy(KCallableImpl.kt:112)
  at kotlin.reflect.full.KCallables.callSuspendBy(KCallables.kt:71)
  at klite.annotations.AnnotationsKt$toHandler$1.invokeSuspend(Annotations.kt:74)
Caused by: java.io.InterruptedIOException: timeout
  at okhttp3.internal.connection.RealCall.timeoutExit(RealCall.kt:398)
  at okhttp3.internal.connection.RealCall.callDone(RealCall.kt:360)
  at okhttp3.internal.connection.RealCall.noMoreExchanges$okhttp(RealCall.kt:325)
  at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:209)
  at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
  at eu.webeid.security.validator.ocsp.OcspClientImpl.request(OcspClientImpl.java:75)
  at eu.webeid.security.validator.certvalidators.SubjectCertificateNotRevokedValidator.validateCertificateNotRevoked(SubjectCertificateNotRevokedValidator.java:102)
  at eu.webeid.security.validator.certvalidators.SubjectCertificateValidatorBatch.executeFor(SubjectCertificateValidatorBatch.java:41)
  at eu.webeid.security.validator.AuthTokenValidatorImpl.validateToken(AuthTokenValidatorImpl.java:160)
  at eu.webeid.security.validator.AuthTokenValidatorImpl.validate(AuthTokenValidatorImpl.java:120)
  at signing.WebEidClient.auth(WebEidClient.kt:40)
  at auth.AuthRoutes.webEIdLogin(AuthRoutes.kt:55)
  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
  at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.base/java.lang.reflect.Method.invoke(Method.java:568)
  at kotlin.reflect.jvm.internal.calls.CallerImpl$Method.callMethod(CallerImpl.kt:97)
  at kotlin.reflect.jvm.internal.calls.CallerImpl$Method$Instance.call(CallerImpl.kt:113)
  at kotlin.reflect.jvm.internal.KCallableImpl.call(KCallableImpl.kt:108)
  at kotlin.reflect.jvm.internal.KCallableImpl.callDefaultMethod$kotlin_reflection(KCallableImpl.kt:159)
  at kotlin.reflect.jvm.internal.KCallableImpl.callBy(KCallableImpl.kt:112)
  at kotlin.reflect.full.KCallables.callSuspendBy(KCallables.kt:71)
  at klite.annotations.AnnotationsKt$toHandler$1.invokeSuspend(Annotations.kt:74)
Caused by: java.io.IOException: Canceled
  at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:72)
  at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
  at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
  at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
  at eu.webeid.security.validator.ocsp.OcspClientImpl.request(OcspClientImpl.java:75)
  at eu.webeid.security.validator.certvalidators.SubjectCertificateNotRevokedValidator.validateCertificateNotRevoked(SubjectCertificateNotRevokedValidator.java:102)
  at eu.webeid.security.validator.certvalidators.SubjectCertificateValidatorBatch.executeFor(SubjectCertificateValidatorBatch.java:41)
  at eu.webeid.security.validator.AuthTokenValidatorImpl.validateToken(AuthTokenValidatorImpl.java:160)
  at eu.webeid.security.validator.AuthTokenValidatorImpl.validate(AuthTokenValidatorImpl.java:120)
  at signing.WebEidClient.auth(WebEidClient.kt:40)
  at auth.AuthRoutes.webEIdLogin(AuthRoutes.kt:55)
  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
  at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.base/java.lang.reflect.Method.invoke(Method.java:568)
  at kotlin.reflect.jvm.internal.calls.CallerImpl$Method.callMethod(CallerImpl.kt:97)
  at kotlin.reflect.jvm.internal.calls.CallerImpl$Method$Instance.call(CallerImpl.kt:113)
  at kotlin.reflect.jvm.internal.KCallableImpl.call(KCallableImpl.kt:108)
  at kotlin.reflect.jvm.internal.KCallableImpl.callDefaultMethod$kotlin_reflection(KCallableImpl.kt:159)
  at kotlin.reflect.jvm.internal.KCallableImpl.callBy(KCallableImpl.kt:112)
  at kotlin.reflect.full.KCallables.callSuspendBy(KCallables.kt:71)
  at klite.annotations.AnnotationsKt$toHandler$1.invokeSuspend(Annotations.kt:74)
```

**Comment by tenor-dev** [comment]
At the very least it would be nice to provide a way to substitute your own OcspClient implementation.

Currently we have to just replace OcspClientImpl in our classpath with our own class to make it work with Java Http Client and our proxy (that also required authentication):
```kotlin
package eu.webeid.security.validator.ocsp

import app.createProxyHttpClient
import app.httpClientBuilder
import app.staticProxy
import org.bouncycastle.cert.ocsp.OCSPReq
import org.bouncycastle.cert.ocsp.OCSPResp
import java.io.IOException
import java.net.URI
import java.net.http.HttpClient
import java.net.http.HttpRequest
import java.net.http.HttpRequest.BodyPublishers.ofByteArray
import java.net.http.HttpResponse.BodyHandlers
import java.time.Duration

class OcspClientImpl private constructor(private val http: HttpClient): OcspClient {
  private val OCSP_REQUEST_TYPE = "application/ocsp-request"
  private val OCSP_RESPONSE_TYPE = "application/ocsp-response"

  override fun request(uri: URI, ocspReq: OCSPReq): OCSPResp {
    val req = HttpRequest.newBuilder().uri(uri)
      .setHeader("Content-Type", OCSP_REQUEST_TYPE).setHeader("Accept", OCSP_RESPONSE_TYPE)
      .timeout(Duration.ofSeconds(10))
      .POST(ofByteArray(ocspReq.encoded)).build()

    val res = http.send(req, BodyHandlers.ofByteArray())
    if (res.statusCode() != 200) throw IOException("OCSP request was not successful, response: ${res.statusCode()}")
    require(res.headers().firstValue("Content-Type").get() == OCSP_RESPONSE_TYPE) { "Invalid response content type" }
    return OCSPResp(res.body())
  }

  companion object {
    @JvmStatic fun build(timeout: Duration?): OcspClient = OcspClientImpl(createProxyHttpClient(timeout))
  }
}
```

**Comment by mrts** [comment]
Thank you for your efforts! I agree with your concerns and the HttpClient-based implementation is the way to go sooner rather than later in the next major version. We still have to figure out the Java 8 compatibility story though. 

> At the very least it would be nice to provide a way to substitute your own OcspClient implementation.

That's a great idea! Do you care to provide a pull request?

**Comment by mrts** [comment]
> At the very least it would be nice to provide a way to substitute your own OcspClient implementation.

I implemented this in https://github.com/web-eid/web-eid-authtoken-validation-java/pull/33. Can you please review if this suits your needs?

**Comment by tenor-dev** [comment]
> This is now implemented in #33. Can you please review the pull request?

Thanks, we have added comments

**Comment by mrts** [comment]
@tenor-dev, version [v2.1.0 has now been released](https://github.com/web-eid/web-eid-authtoken-validation-java/releases/tag/v2.1.0) with this change. Hope this helps!

**Comment by mrts** [comment]
Using Java 11 and the built-in `HttpClient` is coming in #43. Review welcome, especially catching `InterruptedException` and rethrowing it as `IOException`. I'm assuming that the interruption is a rare event and developers just want to treat it like any other I/O failure, so it is simpler to handle it within `BuiltinHttpClientOcspClient.request()`.
